main: com.fpghoti.classicswords.ClassicSwordsMain
version: ${project.version}
api-version: 1.15
name: ClassicSwords
descripion: Bring back the old combat!
commands:
  CSword:
    description: Spawns a CSword