main: com.fpghoti.classicswords.ClassicSwordsMain
version: BETA-1.0
api-version: 1.13
name: ClassicSwords
descripion: Bring back the old combat!
commands:
  CSword:
    description: Spawns a CSword